const ROLES = {
  agent: {
    label: "Agent",
    em: "🎧",
    home: "agentdash",
    perms: ["home", "live", "agentconvo", "kb", "agentdash", "library"],
    desc: "Handle calls, get live AI script guidance, view coaching notes, and track quality.",
  },
  evaluator: {
    label: "Evaluator",
    em: "✅",
    home: "evaldash",
    perms: [
      "home",
      "agentconvo",
      "batch",
      "kb",
      "leader",
      "team",
      "library",
      "evaldash",
      "insights",
    ],
    desc: "Review & score interactions, auto gap analysis, send evals to Supervisor, recommend enrollment, view insights.",
  },
  supervisor: {
    label: "Supervisor",
    em: "🧑‍✈️",
    home: "supervisordash",
    perms: [
      "home",
      "supervisordash",
      "supqueue",
      "sup",
      "live",
      "agentconvo",
      "library",
      "team",
      "leader",
      "frauddash",
      "kb",
      "insights",
    ],
    desc: "Receive QA evals, add feedback, notify QA, coach agents, monitor teams, and read insights.",
  },
  trainer: {
    label: "Trainer",
    em: "🧑‍🏫",
    home: "trainerdash",
    perms: ["home", "trainerdash", "kb", "library", "leader", "insights"],
    desc: "Manage training topics (Markdown), receive enrollment recommendations, and coach agents.",
  },
  fraud: {
    label: "Fraud Analyst",
    em: "🛡️",
    home: "frauddash",
    perms: ["home", "fraud", "sup", "library", "frauddash", "kb"],
    desc: "Monitor fraud signals, manage rules, review high-risk interactions.",
  },
  admin: {
    label: "Admin",
    em: "👑",
    home: "admindash",
    perms: [
      "home",
      "live",
      "agentconvo",
      "batch",
      "agentdb",
      "team",
      "kb",
      "fraud",
      "sup",
      "leader",
      "library",
      "settings",
      "access",
      "audit",
      "admindash",
      "evaldash",
      "frauddash",
      "agentdash",
      "supervisordash",
      "supqueue",
      "trainerdash",
      "insights",
    ],
    desc: "Full access to every dashboard, config, users & audit.",
  },
};
const PERM_LABELS = {
  home: "🏠 Home",
  live: "🎙️ Live Voice",
  agentconvo: "🎬 Agent Convo",
  batch: "📤 Batch",
  agentdb: "👥 Agent DB",
  team: "🏢 Team",
  kb: "📚 KB",
  fraud: "🛡️ Fraud",
  sup: "🎧 Sup Live",
  leader: "🏆 Leaderboard",
  library: "📁 Interactions",
  settings: "⚙️ Setup",
  access: "🔐 Access",
  audit: "🧾 Audit",
  admindash: "👑 Admin",
  evaldash: "✅ Evaluator",
  frauddash: "🛡️ Fraud Dash",
  agentdash: "🎧 Agent",
  supervisordash: "🧑‍✈️ Supervisor",
  supqueue: "📥 Eval Inbox",
  trainerdash: "🧑‍🏫 Trainer",
  insights: "📈 Insights",
};
const NAV_ITEMS = [
  ["home", "🏠 Home"],
  ["agentdash", "🎧 My Dashboard"],
  ["evaldash", "✅ Evaluator"],
  ["supervisordash", "🧑‍✈️ Supervisor"],
  ["supqueue", "📥 Eval Inbox"],
  ["trainerdash", "🧑‍🏫 Trainer"],
  ["frauddash", "🛡️ Fraud Analyst"],
  ["admindash", "👑 Admin"],
  ["insights", "📈 Insights"],
  ["live", "🎙️ Live Voice"],
  ["agentconvo", "🎬 Live Agent Convo"],
  ["batch", "📤 Batch Upload"],
  ["agentdb", "👥 Agent Database"],
  ["team", "🏢 Team Dashboard"],
  ["kb", "📚 Knowledge Base"],
  ["fraud", "🛡️ Fraud"],
  ["sup", "🎧 Supervisor Live"],
  ["leader", "🏆 Leaderboard"],
  ["library", "📁 Interactions"],
  ["access", "🔐 Access Mgmt"],
  ["audit", "🧾 Audit Log"],
  ["settings", "⚙️ Setup"],
];
